# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JWDVideoPlayer' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for JWDVideoPlayer

pod 'Masonry'

  target 'JWDVideoPlayerTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JWDVideoPlayerUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
